# Generated by Django 5.2.8 on 2025-11-14 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('exact_name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('ELEC', 'Electronics'), ('COMP', 'Computers & Accessories'), ('PT', 'Phones & Tablets'), ('HK', 'Home & Kitchen'), ('FURN', 'Furniture'), ('CLOTH', 'Clothing & Accessories'), ('SHOES', 'Shoes'), ('JW', 'Jewelry & Watches'), ('SO', 'Sports & Outdoors'), ('AUTO', 'Automotive'), ('TOOL', 'Tools & Home Improvement'), ('TG', 'Toys & Games'), ('BM', 'Books & Media'), ('MI', 'Musical Instruments'), ('COLL', 'Collectibles'), ('ART', 'Art'), ('ANT', 'Antiques'), ('HB', 'Health & Beauty'), ('PS', 'Pet Supplies'), ('RE', 'Real Estate'), ('IB', 'Industrial & Business'), ('FB', 'Food & Beverages'), ('NULL', 'No Category Listed')], default='No Category Listed', max_length=20)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
