# Generated by Django 5.2.8 on 2025-11-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='listing_images/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('COMP', 'Computers & Accessories'), ('PT', 'Phones & Tablets'), ('HK', 'Home & Kitchen'), ('FURN', 'Furniture'), ('CLOTH', 'Clothing & Accessories'), ('SHOES', 'Shoes'), ('JW', 'Jewelry & Watches'), ('SO', 'Sports & Outdoors'), ('AUTO', 'Automotive'), ('TOOL', 'Tools & Home Improvement'), ('TG', 'Toys & Games'), ('BM', 'Books & Media'), ('MI', 'Musical Instruments'), ('COLL', 'Collectibles'), ('ART', 'Art'), ('ANT', 'Antiques'), ('HB', 'Health & Beauty'), ('PS', 'Pet Supplies'), ('RE', 'Real Estate'), ('IB', 'Industrial & Business'), ('FB', 'Food & Beverages'), ('NULL', 'No Category Listed')], default='NULL', max_length=20),
        ),
    ]
