# Generated by Django 5.2.8 on 2025-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlistings_image_auctionlistings_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
