# Generated by Django 5.2.8 on 2025-11-16 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
