# Generated by Django 5.2.8 on 2025-11-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlistings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
