# Generated by Django 6.0 on 2026-01-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_like_unique_together_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
